[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strato = { path = "../strato" }
getrandom = { version = "0.2.7", features = ["js"] }
leptos = { version = "0.8.14", features = ["csr"] }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
